apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes the database server
  creationTimestamp: null
  labels:
    app: nodejs-ex
    template: nodejs-ex
  name: mongodb
spec:
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: mongodb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}